### ISSUE TITLE
Demo page shows wrong alignment

### ISSUE THREAD

**Issue by cheehongw** [RichDom2185/jekyll-fancy-tables#5]
In the demo page showcasing individual cell alignment, the 5th cell has a right alignment instead of the intended center alignment
![image](https://user-images.githubusercontent.com/72195240/234355185-44f43fda-e49b-45fd-a784-53f098f08903.png)

**Comment by RichDom2185** [comment]
Hi, thanks for the spot! I will push a fix shortly!
